name: train-my-model

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest

    steps:
      - uses: actions/checkout@v2

      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # Get DVC 1.0 
          #pip install dvc[s3]
          
          # install requirements
          pip install -r requirements.txt


          
          # run Data Preparation
          python prepare_data.py
          python model.py
          python strategy_one.py
          python historical_analysis.py
          # Reproduce pipeline if any changes detected in dependencies
          cat testscore.txt >> report.md
          cat score.txt >> score.md
          cat historical_score_GER.txt >> history_GER.md
          cml-publish output_GER.png --md >> history_GER.md
          cat historical_score_ENG.txt >> history_ENG.md
          cml-publish output_ENG.png --md >> history_ENG.md
          # Use DVC metrics diff to compare metrics to master
          #git fetch --prune --unshallow
          #dvc metrics diff --show-md master >> report.md
          cml-send-comment report.md 
          cml-send-comment score.md
          cml-send-comment history_GER.md
          cml-send-comment history_ENG.md

          # Add figure to report
          #dvc plots diff --target loss.csv --show-vega master > vega.json
          #vl2png vega.json -s 1.5 | cml-publish --md  >> report.md
          #cml-send-comment report.md 
