name: train-my-model

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest

    steps:
      - uses: actions/checkout@v2

      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # Get DVC 1.0 
          #pip install dvc[s3]
          
          # install requirements
          pip install -r requirements.txt


          
          # run Data Preparation
          python prepare_data.py
          #python model.py
          #python strategy_one.py
          python analysis_loop.py
          
          # Reproduce pipeline if any changes detected in dependencies
          cat testscore.txt >> report.md
          cat score.txt >> score.md

          cml-publish output_BELGIEN_2015_2016.csv.png --md >> score.md
          cml-publish output_BELGIEN_2016_2017.csv.png --md >> score.md
          cml-publish output_BELGIEN_2017_2018.csv.png --md >> score.md
          cml-publish output_BELGIEN_2018_2019.csv.png --md >> score.md

          cml-publish output_FL_2015_2016.csv.png --md >> score.md
          cml-publish output_FL_2016_2017.csv.png --md >> score.md
          cml-publish output_FL_2017_2018.csv.png --md >> score.md
          cml-publish output_FL_2018_2019.csv.png --md >> score.md

          cml-publish output_GER_BL_2015_2016.csv.png --md >> score.md
          cml-publish output_GER_BL_2016_2017.csv.png --md >> score.md
          cml-publish output_GER_BL_2017_2018.csv.png --md >> score.md
          cml-publish output_GER_BL_2018_2019.csv.png --md >> score.md
          cml-publish output_GER_BL_2019_2020.csv.png --md >> score.md

          cml-publish output_IL_2015_2016.csv.png --md >> score.md
          cml-publish output_IL_2016_2017.csv.png --md >> score.md
          cml-publish output_IL_2017_2018.csv.png --md >> score.md
          cml-publish output_IL_2018_2019.csv.png --md >> score.md
          cml-publish output_IL_2019_2020.csv.png --md >> score.md

          cml-publish output_NL_2015_2016.csv.png --md >> score.md
          cml-publish output_NL_2016_2017.csv.png --md >> score.md
          cml-publish output_NL_2017_2018.csv.png --md >> score.md
          cml-publish output_NL_2018_2019.csv.png --md >> score.md

          cml-publish output_PL_2015_2016.csv.png --md >> score.md
          cml-publish output_PL_2016_2017.csv.png --md >> score.md
          cml-publish output_PL_2017_2018.csv.png --md >> score.md
          cml-publish output_PL_2018_2019.csv.png --md >> score.md
          cml-publish output_PL_2019_2020.csv.png --md >> score.md

          cml-publish output_SL_2015_2016.csv.png --md >> score.md
          cml-publish output_SL_2016_2017.csv.png --md >> score.md
          cml-publish output_SL_2017_2018.csv.png --md >> score.md
          cml-publish output_SL_2018_2019.csv.png --md >> score.md
          cml-publish output_SL_2019_2020.csv.png --md >> score.md  
          
          # Use DVC metrics diff to compare metrics to master
          #git fetch --prune --unshallow
          #dvc metrics diff --show-md master >> report.md
          cml-send-comment report.md 
          cml-send-comment score.md

          # Add figure to report
          #dvc plots diff --target loss.csv --show-vega master > vega.json
          #vl2png vega.json -s 1.5 | cml-publish --md  >> report.md
          #cml-send-comment report.md 
