name: train-my-model

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest

    steps:
      - uses: actions/checkout@v2

      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # Get DVC 1.0 
          #pip install dvc[s3]
          
          # install requirements
          pip install -r requirements.txt


          
          # run Data Preparation
          python prepare_data.py
          #python model.py
          #python strategy_one.py
          python analysis_loop.py
          
          # Reproduce pipeline if any changes detected in dependencies
          cat testscore.txt >> report.md
          cat score.txt >> score.md

          cml-publish output_1.png --md >> score.md
          cml-publish output_2.png --md >> score.md
          cml-publish output_3.png --md >> score.md
          cml-publish output_4.png --md >> score.md

          cml-publish output_5.png --md >> score.md
          cml-publish output_6.png --md >> score.md
          cml-publish output_7.png --md >> score.md
          cml-publish output_8.png --md >> score.md

          cml-publish output_9.png --md >> score.md
          cml-publish output_10.png --md >> score.md
          cml-publish output_11.png --md >> score.md
          cml-publish output_12.png --md >> score.md
          cml-publish output_13.png --md >> score.md

          cml-publish output_14.png --md >> score.md
          cml-publish output_15.png --md >> score.md
          cml-publish output_16.png --md >> score.md
          cml-publish output_17.png --md >> score.md
          cml-publish output_18.png --md >> score.md

          cml-publish output_19.png --md >> score.md
          cml-publish output_20.png --md >> score.md
          cml-publish output_21.png --md >> score.md
          cml-publish output_22.png --md >> score.md

          cml-publish output_23.png --md >> score.md
          cml-publish output_24.png --md >> score.md
          cml-publish output_25.png --md >> score.md
          cml-publish output_26.png --md >> score.md
          cml-publish output_27.png --md >> score.md

          cml-publish output_28.png --md >> score.md
          cml-publish output_29.png --md >> score.md
          cml-publish output_30.png --md >> score.md
          cml-publish output_31.png --md >> score.md
          cml-publish output_32.png --md >> score.md  
          
          # Use DVC metrics diff to compare metrics to master
          #git fetch --prune --unshallow
          #dvc metrics diff --show-md master >> report.md
          cml-send-comment report.md 
          cml-send-comment score.md

          # Add figure to report
          #dvc plots diff --target loss.csv --show-vega master > vega.json
          #vl2png vega.json -s 1.5 | cml-publish --md  >> report.md
          #cml-send-comment report.md 
